[package]
name = "yew-agent"
version = "0.1.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
edition = "2021"
readme = "../../README.md"
description = "Agents for Yew"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { version = "0.19.3", path = "../yew" }
gloo-worker = { git = "https://github.com/futursolo/gloo", branch = "worker-v2", features = ["futures"] }
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
futures = "0.3"
wasm-bindgen-futures = "0.4"
pin-project = "1.0.10"
yew-agent-macro = { version = "0.1", path = "../yew-agent-macro" }
