[package]
name = "yew"
version = "0.19.3"
edition = "2021"
authors = [
  "Denis Kolodin <deniskolodin@gmail.com>",
  "Justin Starry <justin@yew.rs>",
]
repository = "https://github.com/yewstack/yew"
homepage = "https://github.com/yewstack/yew"
documentation = "https://docs.rs/yew/"
license = "MIT OR Apache-2.0"
keywords = ["web", "webasm", "javascript"]
categories = ["gui", "wasm", "web-programming"]
description = "A framework for making client-side single-page apps"
readme = "../../README.md"
rust-version = "1.56.0"

[dependencies]
console_error_panic_hook = "0.1"
gloo = "0.6"
gloo-utils = "0.1.0"
indexmap = { version = "1", features = ["std"] }
js-sys = "0.3"
slab = "0.4"
wasm-bindgen = "0.2"
yew-macro = { version = "^0.19.0", path = "../yew-macro" }
thiserror = "1.0"

futures = { version = "0.3", optional = true }
html-escape = { version = "0.2.9", optional = true }

[dependencies.web-sys]
version = "0.3"
features = [
  "AnimationEvent",
  "Document",
  "DragEvent",
  "Element",
  "ErrorEvent",
  "Event",
  "EventInit",
  "EventTarget",
  "FocusEvent",
  "HtmlElement",
  "InputEvent",
  "InputEventInit",
  "KeyboardEvent",
  "Location",
  "MouseEvent",
  "Node",
  "NodeList",
  "PointerEvent",
  "ProgressEvent",
  "Text",
  "TouchEvent",
  "TransitionEvent",
  "UiEvent",
  "WheelEvent",
  "Window",
  "HtmlVideoElement",
  "HtmlAudioElement",
  "HtmlInputElement",
  "HtmlMetaElement",
  "HtmlDialogElement",
  "HtmlImageElement",
  "HtmlMediaElement",
  "HtmlMapElement",
  "HtmlTableColElement",
  "HtmlLinkElement",
  "HtmlTableCaptionElement",
  "HtmlAreaElement",
  "HtmlTemplateElement",
  "HtmlUListElement",
  "HtmlMenuItemElement",
  "HtmlDivElement",
  "HtmlTableCellElement",
  "HtmlParamElement",
  "HtmlObjectElement",
  "HtmlTextAreaElement",
  "HtmlOptGroupElement",
  "HtmlTimeElement",
  "HtmlHeadElement",
  "HtmlScriptElement",
  "HtmlPictureElement",
  "HtmlDataListElement",
  "HtmlLabelElement",
  "HtmlHeadingElement",
  "HtmlFieldSetElement",
  "HtmlButtonElement",
  "HtmlQuoteElement",
  "HtmlHtmlElement",
  "HtmlCanvasElement",
  "HtmlFormElement",
  "HtmlFrameElement",
  "HtmlHrElement",
  "HtmlDetailsElement",
  "HtmlBodyElement",
  "HtmlStyleElement",
  "HtmlEmbedElement",
  "HtmlTableSectionElement",
  "HtmlTrackElement",
  "HtmlDataElement",
  "HtmlIFrameElement",
  "HtmlOptionElement",
  "HtmlSpanElement",
  "HtmlOListElement",
  "HtmlUnknownElement",
  "HtmlFontElement",
  "HtmlLiElement",
  "HtmlDListElement",
  "HtmlSelectElement",
  "HtmlBrElement",
  "HtmlModElement",
  "HtmlProgressElement",
  "HtmlLegendElement",
  "HtmlSlotElement",
  "HtmlOutputElement",
  "HtmlAnchorElement",
  "HtmlDirectoryElement",
  "HtmlTableElement",
  "HtmlFrameSetElement",
  "HtmlTableRowElement",
  "HtmlSourceElement",
  "HtmlTitleElement",
  "HtmlBaseElement",
  "HtmlParagraphElement",
  "HtmlMeterElement",
  "HtmlPreElement",
  "HtmlMenuElement",
  # "SvgTextElement",
  # "SvgtSpanElement",
  # "SvgRectElement",
  # "SvgPathElement",
  # "SvgLineElement",
  # "SvgEllipseElement",
  # "SvgPolygonElement",
  # "SvgTextPositioningElement",
  # "SvgPolylineElement",
  # "SvgTextPathElement",
  # "SvgCircleElement",
  # "SvgTextContentElement",
  # "SvgfeFuncBElement",
  # "SvgAnimateMotionElement",
  # "SvgLinearGradientElement",
  # "SvgDefsElement",
  # "SvgImageElement",
  # "SvgfeFuncGElement",
  # "SvgAnimateElement",
  # "SvgsvgElement",
  # "SvgForeignObjectElement",
  # "SvggElement",
  # "SvgRadialGradientElement",
  # "SvgAnimateTransformElement",
  # "SvgUseElement",
  # "SvgfeFuncRElement",
  # "SvgSwitchElement",
  # "SvgSetElement",
  # "SvgfeFuncAElement",
  # "SvgGeometryElement",
  # "SvgaElement",
  # "SvgfeGaussianBlurElement",
  # "SvgGradientElement",
  # "SvgfeDropShadowElement",
  # "SvgMetadataElement",
  # "SvgfePointLightElement",
  # "SvgStyleElement",
  # "SvgFilterElement",
  # "SvgfeDisplacementMapElement",
  # "SvgfeDiffuseLightingElement",
  # "SvgmPathElement",
  # "SvgClipPathElement",
  # "SvgfeConvolveMatrixElement",
  # "SvgViewElement",
  # "SvgSymbolElement",
  # "SvgfeCompositeElement",
  # "SvgTitleElement",
  # "SvgMaskElement",
  # "SvgDescElement",
  # "SvgfeSpecularLightingElement",
  # "SvgPatternElement",
  # "SvgMarkerElement",
  # "SvgfeMergeElement",
  # "SvgfeTileElement",
  # "SvgfeColorMatrixElement",
  # "SvgfeSpotLightElement",
  # "SvgStopElement",
  # "SvgfeMorphologyElement",
  # "SvgfeDistantLightElement",
  # "SvgfeMergeNodeElement",
  # "SvgfeComponentTransferElement",
  # "SvgfeOffsetElement",
  # "SvgComponentTransferFunctionElement",
  # "SvgAnimationElement",
  # "SvgfeImageElement",
  # "SvgfeFloodElement",
  # "SvgfeBlendElement",
  # "SvgfeTurbulenceElement",
  # "SvgScriptElement",
  # "SvgGraphicsElement",
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
# we move it here so no promise-based spawn_local can present for
# non-wasm32 targets.
wasm-bindgen-futures = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.15.0", features = ["rt"], optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"
gloo = { version = "0.6", features = ["futures"] }
wasm-bindgen-futures = "0.4"
rustversion = "1"
trybuild = "1"

[dev-dependencies.web-sys]
version = "0.3"
features = [
  "ShadowRoot",
  "ShadowRootInit",
  "ShadowRootMode",
]

[features]
ssr = ["futures", "html-escape"]
csr = []
hydration = ["csr"]
trace_hydration = ["hydration"]
doc_test = ["csr", "hydration", "ssr"]
wasm_test = ["csr", "hydration", "ssr"]
default = []

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1.15.0", features = ["full"] }

[package.metadata.docs.rs]
features = ["doc_test"]
rustdoc-args = ["--cfg", "documenting"]
