[target.'cfg(target_arch = "wasm32")']
runner = 'wasm-bindgen-test-runner'

[unstable]
doctest-xcompile = true
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
share-generics = true
