[package]
name = "benchmark-ssr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { path = "../../packages/yew", features = ["tokio", "ssr"] }
function_router = { path = "../../examples/function_router" }
tokio = { version = "1.19", features = ["full"] }
jemallocator = "0.5.0"
